name: Dockerfile
website_url: https://github.com/typecho/Dockerfile
source_code_url: https://github.com/typecho/Dockerfile
description: Dockerfile 是一个自托管的  应用。
licenses:
  - MIT
platforms:
  - Docker
tags:
  - 容器
