name: Dockerfile
website_url: https://github.com/typecho/Dockerfile
source_code_url: https://github.com/typecho/Dockerfile
description: Docker 容器管理和部署平台。
licenses:
  - MIT
platforms:
  - Docker
tags:
  - 容器
