name: Dockerfile
website_url: https://github.com/typecho/Dockerfile
source_code_url: https://github.com/typecho/Dockerfile
description: Dockerfile 是一个自托管的  应用。
licenses:
  - MIT
platforms:
  - Docker
tags:
  - 容器
stargazers_count: 119
updated_at: '2025-06-03'
archived: false
commit_history:
  2026-05: 0
  2026-06: 0
  2026-07: 0
