name: MkDocs
website_url: https://www.mkdocs.org
source_code_url: https://github.com/mkdocs/mkdocs
description: 基于 Markdown 的项目文档生成器，简洁快速。
licenses:
  - Apache-2.0
platforms:
  - Docker
tags:
  - 知识管理
stargazers_count: 22260
updated_at: '2025-10-20'
archived: false
current_release:
  tag: 1.6.1
  published_at: '2024-08-30'
commit_history:
  2026-05: 0
  2026-06: 0
  2026-07: 0
