name: SWAG (Secure Web Application Gateway)
website_url: https://github.com/linuxserver/docker-swag
description: Nginx webserver 和带有 PHP 支持的反向代理，内置 Certbot（Let's Encrypt）客户端和 fail2ban 集成。
licenses:
  - GPL-3.0
platforms:
  - Docker
tags:
  - Web 服务器
source_code_url: https://github.com/linuxserver/docker-swag
stargazers_count: 3354
updated_at: '2025-07-26'
archived: false
